2025-10-23 07:10:33,690 - INFO - PostgreSQL service is running.
2025-10-23 07:10:33,711 - INFO - Successfully connected to database.
2025-10-23 07:10:33,727 - INFO - Database table schema verified.
2025-10-23 07:13:41,480 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='192.168.0.240', port=80): Read timed out. (read timeout=5)")': /api/v1/data
2025-10-23 07:13:48,703 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='192.168.0.240', port=80): Read timed out. (read timeout=5)")': /api/v1/data
2025-10-23 07:20:56,895 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='192.168.0.240', port=80): Read timed out. (read timeout=5)")': /api/v1/data
2025-10-23 07:21:01,903 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9dea46010>, 'Connection to 192.168.0.240 timed out. (connect timeout=3)')': /api/v1/data
2025-10-23 07:21:08,909 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9dea442d0>, 'Connection to 192.168.0.240 timed out. (connect timeout=3)')': /api/v1/data
